
## <font color='red'> FUNCTIONS, FILTERS AND LAMBDA EXPRESSIONS  </font> 

In [ ]:
# Question 1

In [7]:
def square():
    
    try:
        
        num = float(input("Enter a number:  "))
        squre_1 = num ** 2

        print("The square of {} is {}".format(num, squre_1))

    except ValueError:
            print("Invalid input. please enter a valid number.")

square()
    


Enter a number:  4
The square of 4.0 is 16.0


# <font color='blue'> 2. WRITE A FUNCTION THAT TAKES 2 VARIABLE AND OBTAIN THE SUMMATION AND MULTIPLICATION, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER (REPEAT USING LAMBDA EXPRESSIONS)

# LAMBDA

In [15]:
def function_1(a,b):
    summation =   a + b
    multiplication = a * b
    return summation, multiplication

function_1_lambda = lambda a,b: (a + b, a * b)

num1 =float(input("Enter the first number: "))
num2 =float(input("Enter the second number: "))
sum_, multiply_ = function_1(num1, num2)
print("sum: {}, muliplication: {}".format(sum_ , multiply_)) 

num3 = float(input("Enter the third number: "))
num4 = float(input("Enter the forth number: "))
sum_3, multiply_4 = function_1_lambda(num3,num4)
print("sum (LAMBDA): {},multiplication (LAMBDA): {}".format(sum_3,multiply_4))

Enter the first number: 8
Enter the second number: 8
sum: 16.0, muliplication: 64.0
Enter the third number: 8
Enter the forth number: 8
sum (LAMBDA): 16.0,multiplication (LAMBDA): 64.0


#  <font color='blue'>3. WRITE A FUNCTION THAT TAKES A VARIABLE AND RETURNS ITS FACTORIAL </font> 

In [38]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return  n * factorial(n-1)
a = int(input("Enter the number"))
result = factorial(a)
print("the factorial of {} is {}".format(a,result))

Enter the number4
the factorial of 4 is 24


# <font color='blue'> 4. DEVELOP A SCRIPT WHOSE ITEMS ARE SQUARES OF THE ORIGINAL LIST </font> 

In [ ]:
def square_list(numbers):
    squared_values = [num ** 2 for num in numbers]
    return squared_values

# Test the square_list function
original_list = [1, 2, 3, 4, 5]
squared_list = square_list(original_list)
print(f"Original List: {original_list}")
print(f"Squared List: {squared_list}")


# <font color='blue'> 5. WRITE A FUNCTION THAT SQUARES A VARIABLE AND THEN TEST THE FUNCTION USING A LIST OF INTEGER NUMBERS RANGING FROM -20 to 20

In [18]:
def square(n):
    return    n**2
    
list_1 = list(range(-20,20))    
square_result = [square(num) for num in list_1]

for num, squared in zip(list_1, square_result):
    print("The square of {} is {}".format(num,squared))

The square of -20 is 400
The square of -19 is 361
The square of -18 is 324
The square of -17 is 289
The square of -16 is 256
The square of -15 is 225
The square of -14 is 196
The square of -13 is 169
The square of -12 is 144
The square of -11 is 121
The square of -10 is 100
The square of -9 is 81
The square of -8 is 64
The square of -7 is 49
The square of -6 is 36
The square of -5 is 25
The square of -4 is 16
The square of -3 is 9
The square of -2 is 4
The square of -1 is 1
The square of 0 is 0
The square of 1 is 1
The square of 2 is 4
The square of 3 is 9
The square of 4 is 16
The square of 5 is 25
The square of 6 is 36
The square of 7 is 49
The square of 8 is 64
The square of 9 is 81
The square of 10 is 100
The square of 11 is 121
The square of 12 is 144
The square of 13 is 169
The square of 14 is 196
The square of 15 is 225
The square of 16 is 256
The square of 17 is 289
The square of 18 is 324
The square of 19 is 361


# <font color='blue'> 6. WRITE 3 FUNCTIONS THAT TAKE THE RADIUS OF A CIRCLE AND RETURN THE DIAMETER, AREA AND CIRCUMFERENCE, TEST THE FUNCTION USING AN INPUT FROM A USER 

In [6]:
import math

    return 2 * radius

def cal_area(radius):
    return math.pi * radius ** 2

def cal_circumference(radius):
    return 2 * math.pi * radius
radius = float (input("ENTER THE RADIUS OF CIRCLE:  "))

diameter = cal_diameter(radius)
area = cal_area(radius)
circumference = cal_circumference(radius)

print("radius = {}".format(radius))
print("area = {}".format(area))
print("diameter = {}".format(diameter))
print("circumference = {}".format(circumference))
    


ENTER THE RADIUS OF CIRCLE:  5
radius = 5.0
area = 78.53981633974483
diameter = 10.0
circumference = 31.41592653589793


# <font color='blue'> 7. WRITE A CODE THAT TAKES A RANGE FROM A USER (UPPER AND LOWER BOUND) AND RETURNS A LIST OF POSITIVE AND EVEN NUMBERS ONLY

In [2]:
def function_1(lower, upper):
    even_num =[]
    for i in range(lower,upper+1):
        if i > 0 and i%2 == 0:
            even_num.append(i)
    return even_num

try:
    lower_bound = int(input("Enter the lower bound: "))
    upper_bound = int(input("Enter the upper bound: "))
    
    if lower_bound > upper_bound:
        print("Lower bound should be less than or equal to upper bound.")
    elif lower_bound == upper_bound:
        print("you are not allow taking same value of both the bound  ")
    else:
        p_even_num = function_1(lower_bound,upper_bound)
        print("positive even number: {}".format(p_even_num))
except ValueError:
    print("Invalid input. please enter intger value")
    

Enter the lower bound: 4
Enter the upper bound: 44
positive even number: [4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44]


# <font color='blue'> 8. USING FILTER AND LAMBDA EXPRESSION, WRITE A CODE THAT TAKES A LIST OF NUMBERS BELOW AND RETURNS EVEN NUMBERS ONLY

In [18]:
numbers = [2,11,33,44,55,66,77,88,224,26,55,8,10]

even_num = list(filter(lambda x: x % 2 == 0, numbers))

print("Even numbers: {}".format(even_num))


Even numbers: [2, 44, 66, 88, 224, 26, 8, 10]


# <font color='blue'> 9. WRITE A FUNCTION THAT TAKES TWO NUMPY MATRICES AND RETURN THE ADDITION, SUBTRACTION, TRANSPOSE, PRODUCT, DOT PRODUCT

In [40]:
import numpy as np

def matrix(matrix_1,matrix_2):
    addition = matrix_1 + matrix_2
    substraction = matrix_1 - matrix_2
    transpose_1 = np.transpose(matrix_1)
    transpose_2 = np.transpose(matrix_2)
    product = matrix_1 * matrix_2
    dot_product = np.dot(matrix_1,matrix_2)
    
    return addition, substraction, transpose_1, transpose_2 , product ,dot_product

matrix_x = np.array([[1,2], [3,4]])
matrix_y = np.array([[5,6], [7,8]])

addition, substraction, transpose_1, transpose_2 , product ,dot_product = matrix(matrix_x, matrix_y)
print("Matrix addition:\n {}".format(addition))
print("\nMatrix Subtraction:\n {}".format(subtraction))
print("\nTranspose of Matrix 1:\n {}" .format(transpose1))
print("\nTranspose of Matrix 2:\n {}".format(transpose2))
print("\nElement-wise Product:\n {}".format(elementwise_product))
print("\nDot Product:\n {}".format(dot_product))      

Matrix addition:
 [[ 6  8]
 [10 12]]

Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]

Transpose of Matrix 1:
 [[1 3]
 [2 4]]

Transpose of Matrix 2:
 [[5 7]
 [6 8]]

Element-wise Product:
 [[ 5 12]
 [21 32]]

Dot Product:
 [[19 22]
 [43 50]]


# <font color='blue'> 10. WRITE A FUNCTION THAT TAKES TWO VALUES FROM A USER AND SUM THEM UP. IF NO VALUES ARE PROVIDED, ASSUME DEFAULT VALUES OF 3 AND 5

In [49]:
def summition(x=3,y=5):
    return x+y
try:
    value_1 = float(input("Enter the first value (or default): "))
    value_2 = float(input("Enter the second value (or default): "))
except ValueError:
    value_1 = None
    value_2 = None
    
if value_1 is not None and value_2 is not None:
    result = summition(value_1 , value_2)
    print("sum:",result)
    
else:
    result_2 = summition()
    print("sum (using default values):", result_2)

Enter the first value (or default): 
sum (using default values): 8


# <font color='blue'> 11. WRITE A SCRIPT THAT WILL PROMPT A USER FOR A RANGE (MIN/MAX VALUE) AND RETURNS NUMBERS THAT ARE DIVISIBLE BY 4 BUT ARE NOT MULTIPLES OF 3 

In [57]:
def numbers(min_value, max_value):
    filtered_numbers = []
    for num in range(min_value, max_value + 1):
        if num % 4 == 0 and num % 3 != 0:
            filtered_numbers.append(num)
    return filtered_numbers

try:
    min_range = int(input("Enter the minimum value: "))
    max_range = int(input("Enter the maximum value: "))
    
    if min_range > max_range:
        print("Minimum value should be less than or equal to maximum value.")
    else:
        result = numbers(min_range, max_range)
        print("Numbers divisible by 4 but not multiples of 3 {}:".format(result))
except ValueError:
    print("Invalid input. Please enter valid integers for the range.")


Enter the minimum value: 4
Enter the maximum value: 100
Numbers divisible by 4 but not multiples of 3 [4, 8, 16, 20, 28, 32, 40, 44, 52, 56, 64, 68, 76, 80, 88, 92, 100]:


# <font color='blue'> 12. DEFINE AN ENGLISH TO FRENCH TRANSLATOR FUNCTION THAT TAKES AN INPUT FROM A USER AND RETURNS THE TRANSLATION, USE ANY 5 KNOWN WORDS

In [ ]:
def translator(word):
    translations = {
        "hello": "bonjour",
        "goodbye": "au revoir",
        "cat": "chat",
        "dog": "chien",
        "apple": "pomme"
    }
    
    return translations.get(word, "Translation not found")

try:
    user_input = input("Enter a word in English: ")
    translation = translator(user_input.lower())
    print("Translation:", translation)
except KeyError:
    print("Word not found in the dictionary.")
