# 100 numpy exercises


### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anacond

### 3. Create a null vector of size 10 (★☆☆)

In [9]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array (★☆☆)

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

size_bytes = arr.nbytes

size_kilobytes = memory_size_bytes / 1024
size_megabytes = memory_size_kilobytes / 1024

print(" size in bytes:", size_bytes)
print(" size in kilobytes:", size_kilobytes)
print(" size in megabytes:", size_megabytes)


 size in bytes: 20
 size in kilobytes: 0.01953125
 size in megabytes: 1.9073486328125e-05


### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
help(np.add)
python -m pydoc numpy.add


SyntaxError: invalid syntax (1584442970.py, line 2)

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:

x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
x = np.arange(50)
x = x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
nx = np.nonzero([1,2,0,0,4,0])
print(nx)

(array([0, 1, 4], dtype=int64),)


### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
x = np.random.random((3,3,3))
print(x)

[[[0.12012876 0.43198476 0.49652377]
  [0.29898067 0.63882493 0.86533945]
  [0.74328116 0.0283135  0.28546766]]

 [[0.64165905 0.11544787 0.79653363]
  [0.58893173 0.93006307 0.11037692]
  [0.21312059 0.95514878 0.10965099]]

 [[0.35519526 0.3322263  0.8785452 ]
  [0.95166563 0.7687187  0.59954514]
  [0.13107192 0.58764118 0.49646611]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

0.028207268102445116 0.9735372752134926



### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
x = np.random.random(30)
y = x.mean()
print(y)

0.4533856784527766


### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [25]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
y = np.diag(1+np.arange(4),k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [31]:
y = np.zeros((8,8),dtype=int)
y[1::2,::2] = 1
y[::2,1::2] = 1
print(y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix (★☆☆)

In [36]:
x = np.random.random((5,5))
x = (x - np.mean (x)) / (np.std (x))
print(x)

[[-0.7013062  -1.84675128  0.16708874  0.98739479  0.75725439]
 [ 0.43572233  0.87620813  1.41386036 -0.07928261  0.90002347]
 [-0.4151982   1.21720495 -1.4694956   0.64282853  1.29085124]
 [-0.89823049 -1.59093867 -1.12362174  0.32032841  0.37238702]
 [-0.23580258  0.39258992 -0.9218942  -1.63008759  1.13886689]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
a = np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:

a = np.arange(11)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


### 26. What is the output of the following script? (★☆☆)
```python


print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [46]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [47]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [49]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Admin\AppData\Local\Temp\ipykernel_9772\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Admin\AppData\Local\Temp\ipykernel_9772\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Admin\AppData\Local\Temp\ipykernel_9772\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)), x))

print(np.where(x>0, np.ceil(x), np.floor(x)))

[ 10.   7.   6.   8.   5.   2.   5.  -2.  -9. -10.]
[ 10.   7.   6.   8.   5.   2.   5.  -2.  -9. -10.]


### 30. How to find common values between two arrays? (★☆☆)

In [59]:
x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[0 2 3 4 7]


### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [62]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(all="ignore"):
    np.arange(3) / 0

### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [64]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_9772\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [67]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(days=1)

tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-04
Today: 2023-09-05
Tomorrow: 2023-09-06


### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [70]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [71]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [73]:
x = np.random.uniform(0,10,10)

print(x - Z%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[nan nan nan nan nan nan nan nan nan nan]
[5. 4. 1. 6. 2. 5. 1. 6. 5. 2.]
[5. 4. 1. 6. 2. 5. 1. 6. 5. 2.]
[5 4 1 6 2 5 1 6 5 2]
[5. 4. 1. 6. 2. 5. 1. 6. 5. 2.]


C:\Users\Admin\AppData\Local\Temp\ipykernel_9772\2790886191.py:3: RuntimeWarning: invalid value encountered in remainder
  print(x - Z%1)


### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [77]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [80]:
def generate():
    for x in range(10):
        yield x
y = np.fromiter(generate(),dtype=float,count=-1)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [83]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


### 40. Create a random vector of size 10 and sort it (★★☆)

In [85]:
x = np.random.random(10)
x.sort()
print(x)

[0.0893908  0.34529271 0.38777714 0.42466653 0.46433622 0.49156588
 0.56391536 0.64892598 0.84017811 0.89821926]


### 41. How to sum a small array faster than np.sum? (★★☆)

In [5]:
import numpy as np
x = np.arange(10)
np.add.reduce(x)

45

### 42. Consider two random array A and B, check if they are equal (★★☆)

In [6]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)


equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


### 43. Make an array immutable (read-only) (★★☆)

In [7]:
x = np.zeros(10)
x.flags.writeable = False
Z[0] = 1

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [11]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.06659888 0.68411234 0.92510095 1.15236435 0.79088155 0.32087843
 0.57321838 0.73183777 0.20788983 0.71964878]
[1.11129626 0.04057355 0.51121355 0.62400454 0.28607595 1.00269307
 0.90203596 0.50642736 1.03730336 1.15012061]


### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [12]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.31734062 0.33262932 0.44437151 0.         0.46353572 0.35021826
 0.12582622 0.44480188 0.22469467 0.82675548]


### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [13]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [50]:

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


### 49. How to print all the values of an array? (★★☆)

In [52]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [17]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

80


### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [18]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Admin\AppData\Local\Temp\ipykernel_7076\2893404235.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),


### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [5]:
import numpy  as np
a = np.random.random((10,2))
X,Y = np.atleast_2d(a[:,0], a[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.57983198 0.26016654 0.20004523 0.58922629 0.60997187
  0.38266846 0.1949778  0.46591882 0.45808813]
 [0.57983198 0.         0.65816903 0.70827982 0.25689752 0.50885644
  0.54889417 0.63096985 0.21941803 0.12211736]
 [0.26016654 0.65816903 0.         0.43518683 0.75665369 0.83862824
  0.63473827 0.06521788 0.47026145 0.55232616]
 [0.20004523 0.70827982 0.43518683 0.         0.64606946 0.58082244
  0.3205309  0.37259843 0.63795023 0.58829479]
 [0.58922629 0.25689752 0.75665369 0.64606946 0.         0.26228956
  0.38826034 0.71067154 0.42889191 0.25508283]
 [0.60997187 0.50885644 0.83862824 0.58082244 0.26228956 0.
  0.26123871 0.78021254 0.63825937 0.467961  ]
 [0.38266846 0.54889417 0.63473827 0.3205309  0.38826034 0.26123871
  0.         0.57125172 0.58546536 0.45508456]
 [0.1949778  0.63096985 0.06521788 0.37259843 0.71067154 0.78021254
  0.57125172 0.         0.45709525 0.51964427]
 [0.46591882 0.21941803 0.47026145 0.63795023 0.42889191 0.63825937
  0.58546536 0.45709

### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [2]:
import numpy as np
A = (np.random.rand(10)*100).astype(np.float32)
B = A.view(np.int32)
B[:] = A
print(B)

[24 93 63 97  8 12 84 39 74 10]


### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [3]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
a = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(a)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [4]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [59]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

### 57. How to randomly place p elements in a 2D array? (★★☆)

In [13]:
a = 8
b = 4
c = np.zeros((a,a))
np.put(Z, np.random.choice(range(a*a), p, replace=False),1)
print(Z)

[[0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 58. Subtract the mean of each row of a matrix (★★☆)

In [17]:
import numpy as np

matrix = np.array([[7, 5, 7],
                  [7, 8, 9],
                  [6, 5, 4]])

row_means = np.mean(matrix, axis=1)

new_matrix = matrix - row_means[:, np.newaxis]

print(new_matrix)


[[ 0.66666667 -1.33333333  0.66666667]
 [-1.          0.          1.        ]
 [ 1.          0.         -1.        ]]


### 59. How to sort an array by the nth column? (★★☆)

In [28]:
a = np.random.randint(0,20,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[12  5  4]
 [ 2 16 12]
 [ 0 14 18]]
[[12  5  4]
 [ 0 14 18]
 [ 2 16 12]]


### 60. How to tell if a given 2D array has null columns? (★★☆)

In [31]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


### 61. Find the nearest value from a given value in an array (★★☆)

In [41]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4831906665502973





### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [42]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 63. Create an array class that has a name attribute (★★☆)

In [43]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [44]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[6. 2. 2. 3. 6. 2. 3. 2. 2. 2.]
[11.  3.  3.  5. 11.  3.  5.  3.  3.  3.]


### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [68]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [69]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [70]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[59 55 61 40]
 [52 45 62 55]
 [63 56 74 34]]
[[59 55 61 40]
 [52 45 62 55]
 [63 56 74 34]]


### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [71]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.32405276 0.41632549 0.51352229 0.55773555 0.76342123 0.55102833
 0.55299829 0.38927183 0.51715287 0.38034321]
0    0.324053
1    0.416325
2    0.513522
3    0.557736
4    0.763421
5    0.551028
6    0.552998
7    0.389272
8    0.517153
9    0.380343
dtype: float64


### 69. How to get the diagonal of a dot product? (★★★)

In [72]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.04493741, 1.33813764, 1.09863653, 0.67494893, 0.81377143])

### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [73]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [45]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


### 72. How to swap two rows of an array? (★★★)

In [57]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [61]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 66) ( 1, 99) ( 2, 21) ( 2, 93) (13, 19) (13, 23) (16, 48) (16, 66)
 (19, 23) (19, 71) (19, 99) (20, 77) (20, 88) (21, 40) (21, 65) (21, 93)
 (32, 50) (32, 73) (38, 69) (38, 79) (40, 65) (48, 66) (50, 72) (50, 73)
 (50, 83) (66, 99) (69, 79) (71, 99) (72, 83) (77, 88)]


### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [48]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


### 75. How to compute averages using a sliding window over an array? (★★★)

In [49]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [64]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [51]:

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.89861814,  0.75229805,  0.11860884,  0.81870255,  0.58115863,
        0.69525938, -0.93783473,  0.68619504,  0.51256071,  0.52513012,
       -0.33716558,  0.9178051 , -0.35104098, -0.63905835,  0.54310457,
       -0.84825482, -0.80367247,  0.79742416,  0.98566191,  0.34566353,
        0.03119072,  0.25568646,  0.94310308, -0.39355834,  0.7867412 ,
        0.02304783, -0.19694816,  0.56074903,  0.6373281 , -0.28528278,
       -0.37755366, -0.47333518,  0.16544714, -0.67279687,  0.40907544,
        0.2019512 , -0.56109782, -0.98285317, -0.4273668 ,  0.3067253 ,
       -0.59290687, -0.92428524,  0.13382952, -0.3453919 ,  0.60764384,
        0.30660173,  0.2080959 ,  0.4420243 ,  0.93800919, -0.28778062,
        0.64392982,  0.04381358, -0.70931451, -0.18740668,  0.83323489,
       -0.69045961,  0.73396484,  0.38886465, -0.27677164,  0.66688267,
        0.64199713,  0.1553891 , -0.05883225,  0.71014157, -0.76159815,
        0.12491672,  0.64606785, -0.37956708,  0.65615735, -0.58

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [52]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.00885268  0.16071832  9.55743462 13.32950735 11.32686867  0.36942089
 13.17461632  7.95033965  3.57237001  0.46215915]


### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [68]:

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.58122235  4.05335588  8.41534033 16.60788833  8.92661392  7.55017467
   6.21660568  4.38774036  3.83126106 10.3303629 ]
 [ 5.18274897  0.60354068  5.72498043 10.41034915  4.42668088  1.43186435
   1.05907606  0.46163217  0.11232037  4.13308723]
 [ 2.82992787  7.72042974  7.63278039  5.04422006  2.68513204  4.59678932
   0.78849785  0.70616951  6.85293825  1.26192874]
 [ 1.87978843  3.09566038  3.86269502  6.80557763  2.03504246  2.07549998
   2.12456341  2.07777244  1.7878753   0.53051281]
 [ 0.94617479 11.00856069  5.76955334  0.69308455  5.86385351  8.8967186
   4.39364741  2.02823055  9.48654563  5.6130552 ]
 [ 5.37951694  1.22401777  4.81923089 11.50471858  6.26915704  2.75049958
   1.11663438  0.03256763  1.98949364  5.23689802]
 [ 1.1288505  11.08649728  5.63029061  0.52509326  5.93548717  9.05111595
   4.574436    2.19170116  9.52871725  5.78058352]
 [ 1.45543805  1.70898971  0.38113094  5.21031383  3.57176764  3.03759957
   5.64637893  6.1424334   0.39380384  1.04028127]
 

### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [72]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [84]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)


Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 82. Compute a matrix rank (★★★)

In [85]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


### 83. How to find the most frequent value in an array?

In [55]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [56]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[2 3 4]
   [2 0 3]
   [4 3 0]]

  [[3 4 0]
   [0 3 4]
   [3 0 1]]

  [[4 0 4]
   [3 4 3]
   [0 1 4]]

  [[0 4 2]
   [4 3 2]
   [1 4 1]]

  [[4 2 4]
   [3 2 2]
   [4 1 4]]

  [[2 4 2]
   [2 2 0]
   [1 4 2]]

  [[4 2 4]
   [2 0 3]
   [4 2 2]]

  [[2 4 0]
   [0 3 3]
   [2 2 4]]]


 [[[2 0 3]
   [4 3 0]
   [2 1 0]]

  [[0 3 4]
   [3 0 1]
   [1 0 4]]

  [[3 4 3]
   [0 1 4]
   [0 4 1]]

  [[4 3 2]
   [1 4 1]
   [4 1 2]]

  [[3 2 2]
   [4 1 4]
   [1 2 3]]

  [[2 2 0]
   [1 4 2]
   [2 3 0]]

  [[2 0 3]
   [4 2 2]
   [3 0 0]]

  [[0 3 3]
   [2 2 4]
   [0 0 0]]]


 [[[4 3 0]
   [2 1 0]
   [0 0 2]]

  [[3 0 1]
   [1 0 4]
   [0 2 2]]

  [[0 1 4]
   [0 4 1]
   [2 2 0]]

  [[1 4 1]
   [4 1 2]
   [2 0 3]]

  [[4 1 4]
   [1 2 3]
   [0 3 1]]

  [[1 4 2]
   [2 3 0]
   [3 1 2]]

  [[4 2 2]
   [3 0 0]
   [1 2 4]]

  [[2 2 4]
   [0 0 0]
   [2 4 0]]]


 [[[2 1 0]
   [0 0 2]
   [3 2 3]]

  [[1 0 4]
   [0 2 2]
   [2 3 0]]

  [[0 4 1]
   [2 2 0]
   [3 0 0]]

  [[4 1 2]
   [2 0 3]
   [0 0 2]]

  [[1 2 3]
   

### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [88]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 1 15  4  6 11]
 [15  5 12 16  9]
 [ 4 12  6 42  7]
 [ 6 16 42  1  8]
 [11  9  7  8  7]]


### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [89]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [76]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [91]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0

### 89. How to get the n largest values of an array (★★★)

In [92]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9996 9998 9995]


### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [93]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


### 91. How to create a record array from a regular array? (★★★)

In [81]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [95]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.53 s ± 59.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
389 ms ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
222 ms ± 27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [84]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 4 5 6]


### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [97]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 0 4]
 [3 3 4]
 [1 2 4]
 [3 2 1]
 [0 0 3]
 [4 3 0]
 [0 3 1]
 [0 4 0]
 [4 4 0]
 [1 0 3]]
[[3 0 4]
 [3 3 4]
 [1 2 4]
 [3 2 1]
 [0 0 3]
 [4 3 0]
 [0 3 1]
 [0 4 0]
 [4 4 0]
 [1 0 3]]
[[3 0 4]
 [3 3 4]
 [1 2 4]
 [3 2 1]
 [0 0 3]
 [4 3 0]
 [0 3 1]
 [0 4 0]
 [4 4 0]
 [1 0 3]]


### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [87]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [99]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 0 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [93]:

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[1.67337697e-02, 4.29695274e-01, 2.21842145e-01, 8.92054934e-02,
        4.17183432e-01, 4.60846589e-01, 1.90405274e-01, 4.15233934e-01,
        1.20644068e-02, 2.25442445e-01],
       [5.84408015e-03, 1.50066224e-01, 7.74758649e-02, 3.11540115e-02,
        1.45696604e-01, 1.60945469e-01, 6.64968926e-02, 1.45015764e-01,
        4.21335789e-03, 7.87332288e-02],
       [1.60859266e-02, 4.13059745e-01, 2.13253590e-01, 8.57519283e-02,
        4.01032295e-01, 4.43005046e-01, 1.83033789e-01, 3.99158272e-01,
        1.15973368e-02, 2.16714505e-01],
       [1.49645864e-02, 3.84265600e-01, 1.98387812e-01, 7.97742133e-02,
        3.73076577e-01, 4.12123432e-01, 1.70274614e-01, 3.71333191e-01,
        1.07888934e-02, 2.01607468e-01],
       [1.17449207e-02, 3.01589960e-01, 1.55704211e-01, 6.26106053e-02,
        2.92808281e-01, 3.23454115e-01, 1.33639634e-01, 2.91439989e-01,
        8.46763786e-03, 1.58231151e-01],
       [2.94127929e-02, 7.55271428e-01, 3.89929896e-01, 1.56795674e-01,
   

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [96]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [102]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [98]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.10497444  0.27731076]
